title: Mon Portfolio
description: Portfolio professionnel de Data Analyst spécialisé en analyse de données, Business Intelligence et développement.

baseurl: ""
url: "https://camara-lab.github.io"

author:
  name: Josephine Camara
  email: josephine20camara@gmail.com
  github: camara-lab
  linkedin: ton-profil-linkedin
  role: Data Analyst | Systeme D'information

# ----------------------------
# THÈME PROFESSIONNEL
# ----------------------------
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown

# ----------------------------
# Navigation

